version: '3.4'
services:

  fluentbit:
    image: fluent/fluent-bit:0.12
    command: /fluent-bit/bin/fluent-bit
      -i forward
      -o es -p Host=elasticsearch
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    external:
      name: lognet
