version: '3.4'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    container_name: elasticsearch
    labels:
      - traefik.backend=elasticsearch
      - traefik.port=9200
      - traefik.frontend.rule=Host:elasticsearch.docker.localhost
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - ~/esdata:/usr/share/elasticsearch/data

  fluentd:
    build: ./fluentd/
    container_name: fluentd
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./fluentd/:/fluentd/etc/
    environment:
      - FLUENTD_CONF=fluent.conf
    ports:
      - 9880:9880
      - 24224:24224
      - 24224:24224/udp
    labels:
      - traefik.backend=fluentd
      - traefik.port=9880
      - traefik.frontend.rule=Host:fluentd.docker.localhost

  zookeeper: &zookeeper-defaults
    image: zookeeper:3.4.11
    container_name: zookeeper
    depends_on:
      - fluentd
    ports:
      - 2181:2181
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: zookeeper

  mesos-master: &mesos-master-defaults
    image: mesosphere/mesos-master:1.4.0
    container_name: mesos-master
    depends_on:
      - zookeeper
    command:
      --hostname=mesos-master
      --quorum=1
      --work_dir=/var/lib/mesos/master
      --zk=zk://zookeeper:2181/mesos
    labels:
      - traefik.backend=mesos
      - traefik.port=5050
      - traefik.frontend.rule=Host:mesos.docker.localhost
    ports:
      - 5050:5050
    dns: 127.0.0.1
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: mesos_master

  marathon:
    image: mesosphere/marathon:v1.5.2
    container_name: marathon
    depends_on:
      - mesos-master
    command:
      --master local
      --zk zk://zookeeper:2181/marathon
      --http_port 7070
    privileged: true
    environment:
      - zookeeper_nodes_master=zk://zookeeper:2181/mesos
      - zookeeper_nodes=zk://zookeeper:2181/marathon
    labels:
      - traefik.backend=marathon
      - traefik.port=7070
      - traefik.frontend.rule=Host:marathon.docker.localhost
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: marathon

  traefik:
    image: traefik
    container_name: traefik
    command:
      --web
      --docker --docker.domain=docker.localhost
      --logLevel=DEBUG
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - traefik.backend=traefik
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.docker.localhost
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: traefik

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    container_name: kibana
    depends_on:
      - elasticsearch
    labels:
      - traefik.backend=kibana
      - traefik.port=5601
      - traefik.frontend.rule=Host:kibana.docker.localhost
    ports:
      - 5601:5601

  mesos-slave-1: &mesos-slave-defaults
    image: mesosphere/mesos-slave:1.4.0
    container_name: mesos-slave-1
    restart: always
    command:
      --master=zk://zookeeper:2181/mesos
      --no-systemd_enable_support
      --work_dir=/var/lib/mesos/agent
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - fluentd
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: mesos_slave

  # mesos-slave-2:
  #   <<: *mesos-slave-defaults

  # mesos-slave-3:
  #   <<: *mesos-slave-defaults

volumes:
  esdata1:
    driver: local
