version: '3.3'
services:
  logspout:
    build: ./logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ROUTE_URIS=logstash://logstash.docker.localhost:5000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    ports:
      - 9200:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.0
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    labels:
      - traefik.backend=kibana
      - traefik.port=5601
      - traefik.frontend.rule=Host:kibana.docker.localhost
    ports:
      - 5601:5601
  zookeeper: &zookeeper-defaults
    image: zookeeper:3.4.11
    ports:
      - 2181:2181

  mesos-master: &mesos-master-defaults
    image: mesosphere/mesos-master:1.4.0
    command:
      --hostname=mesos-master
      --quorum=1
      --work_dir=/var/lib/mesos/master
      --zk=zk://zookeeper:2181/mesos
    labels:
      - traefik.backend=mesos
      - traefik.port=5050
      - traefik.frontend.rule=Host:mesos.docker.localhost
    ports:
      - 5050:5050
    dns: 127.0.0.1
  marathon:
    image: mesosphere/marathon:v1.5.2
    command:
      --master local
      --zk zk://zookeeper:2181/marathon
      --http_port 7070
    privileged: true
    environment:
      - zookeeper_nodes_master=zk://zookeeper:2181/mesos
      - zookeeper_nodes=zk://zookeeper:2181/marathon
    labels:
      - traefik.backend=marathon
      - traefik.port=7070
      - traefik.frontend.rule=Host:marathon.docker.localhost
  traefik:
    image: traefik
    command:
      --web
      --docker --docker.domain=docker.localhost
      --logLevel=DEBUG
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - traefik.backend=traefik
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.docker.localhost

  mesos-slave-1: &mesos-slave-defaults
    image: mesosphere/mesos-slave:1.4.0
    command:
      --master=zk://zookeeper:2181/mesos
      --no-systemd_enable_support
      --work_dir=/var/lib/mesos/agent
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mesos-slave-2:
    <<: *mesos-slave-defaults

  mesos-slave-3:
    <<: *mesos-slave-defaults
